language: cpp

dist: xenial
addons:
  apt:
    packages:
    - python3-setuptools
    - python3-wheel
    - python3-pip
    - ninja-build

compiler:
  - gcc
  - clang

install:
  - pip3 install meson

script:
  - meson build
  - cd build && ninja test